### ISSUE TITLE
Respect typecasting in ConfigurationUtility

### ISSUE THREAD

**Issue by echavaillaz** [einpraegsam/powermail#306]
Hi,

In the file `ext_conf_template.txt`, you declare all your settings with the type `bool`.
But in `ConfigurationUtility` you make a condition between the value and a string.
When using per example the helhum distribution and having the configuration in yaml we need strict comparison. For exemple I can have : 

```
EXT:
    extConf:
        powermail:
            disableBackendModule: true
            disableIpLog: true
            disableMarketingInformation: true
            disablePluginInformation: false
            disablePluginInformationMailPreview: true
            enableCaching: false
            l10n_mode_merge: false
            replaceIrreWithElementBrowser: false
```

So you need to change all your method `isSettingActive` like this (for example) : 

```
public static function isDisableIpLogActive(): bool
{
    $extensionConfig = self::getExtensionConfiguration();
    return (bool)$extensionConfig['disableIpLog'] === true;
 }
```

I can provide a PR if you need it.
Thanks a lot,
Eric
