### ISSUE TITLE
Add Services.yaml

### ISSUE THREAD

**Issue by Cabag** [einpraegsam/powermail#573]
Please add a Configuration/Services.yaml File so that Dependency Injection can be used when using powermail classes in third party extensions within TYPO3 v10.4
Can be quite simple like
```
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\Powermail\:
    resource: '../Classes/*'
  ```
