### ISSUE TITLE
ReturnPath not working anymore

### ISSUE THREAD

**Issue by Patta** [einpraegsam/powermail#668]
The configured returnPath is not working anymore and the senderEmail is used instead the specific email for return/bounce mails.

TYPO3 10.4.14
powermail 8.3.1
PHP 7.4
Composer mode

Mail system config:
```
MAIL:
    defaultMailFromAddress: site@my.site
    defaultMailFromName: 'My Site'
    transport: smtp
    transport_smtp_encrypt: true
    transport_smtp_password: '123456789'
    transport_smtp_server: 'my.site:465'
    transport_smtp_username: site@my.site
```

This configuration is ignored since powermail 8 and TYPO3 10.4. 
```
plugin.tx_powermail {
    settings.setup {
        receiver {
            overwrite {
                returnPath.value = bounce@my.site
            }
        }
        sender {
            overwrite {
                returnPath.value = bounce@my.site
            }
        }
    }
}
```
The same system and setup config was working with powermail 7 and TYPO3 9.5.
